-- Anonymized production-derived snapshot from 2026-09-28. IDs and ownership are preserved.
SET NAMES utf8mb4;
-- Replays after insert/: duplicate snapshot IDs are ignored.
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (8, NULL, 'กะหล่ำปลี บ้านมณีพฤกษ์', 'กะหล่ำปลี  แปลงพ่อจำลอง บ้านมณีพฤกษ์ ต.งอบ อ.ทุ่งช้าง จ.น่าน', 50.00, 'ผักผลไม้', 'market', NULL, NULL, 0, 0, 11, '2025-11-08 12:50:44', '2025-11-29 11:06:54', 0, 6);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (9, NULL, 'ฟักทอง บ้านขุนสถาน', 'บ้านพ่อเอนก บ้านขุนสถาน ต.สันทะ อ.นาน้อย จ.น่าน', 29.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-08 12:53:13', '2025-11-29 11:06:17', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (10, NULL, 'มะนอยออมแอม บ้านขุนสถาน', 'บวบเหลี่ยม บ้านพ่อเอนก บ้านขุนสถาน ต.สันทะ อ.นาน้อย จ.น่าน\nเป็นผักที่มีลักษณะเด่น คือ เป็นผลสีเขียวมีร่องหรือสันเหลี่ยมตามแนวยาว', 29.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-08 12:56:36', '2025-11-29 11:00:48', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (11, NULL, 'ฟักเขียว บ้านขุนสถาน', 'ฟักเขียว บ้านพ่อเอนก บ้านขุนสถาน ต.สันทะ อ.นาน้อย จ.น่าน\nเป็นผลขนาดใหญ่ ทรงยาวรี สีเขียวอ่อน หรือสีเหลืองอ่อนเมื่อแก่จัด', 49.83, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-08 12:57:34', '2025-11-08 12:57:34', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (12, NULL, 'ยอดฟักทอง บ้านขุนสถาน', 'ยอดฟักทอง บ้านพ่อเอนก บ้านขุนสถาน ต.สันทะ อ.นาน้อย จ.น่าน\nเป็นผักที่นิยมนำมาประกอบอาหาร (เช่น ผัดหรือแกง)', 20.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-08 12:58:30', '2025-11-29 11:06:30', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (13, NULL, 'มะเขือเทศ บ้านปางแก', 'แปลงพ่อดุสิต บ้านปางแก ต.ทุ่งช้าง อ.ทุ่งช้าง จ.น่าน', 50.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-08 21:50:24', '2025-11-08 21:50:24', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (14, NULL, 'คะน้าใบหยิก บ้านปางแก', 'แปลงพ่อดุสิต บ้านปางแก ต.ทุ่งช้าง อ.ทุ่งช้าง จ.น่าน', 50.00, 'ผักผลไม้', 'market', NULL, NULL, 0, 0, 11, '2025-11-08 21:51:35', '2025-11-29 11:07:24', 0, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (15, NULL, 'ผักกาด บ้านปางแก', 'แปลงพ่อดุสิต บ้านปางแก ต.ทุ่งช้าง อ.ทุ่งช้าง จ.น่าน', 50.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-08 21:52:19', '2025-11-08 21:52:19', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (16, NULL, 'ฟักทองเขียว บ้านปางแก', 'แปลงพ่อดุสิต บ้านปางแก ต.ทุ่งช้าง อ.ทุ่งช้าง จ.น่าน', 50.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-08 21:53:05', '2025-11-08 21:53:05', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (17, NULL, 'ลูกพลับ แปลงพ่อทวีชัย', 'แปลงพ่อทวีชัย บ้านมณีพฤกษ์ ต.งอบ อ.ทุ่งช้าง จ.น่าน', 50.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-08 22:09:00', '2025-11-08 22:09:00', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (18, NULL, 'ขิง แปลงพ่อทวีชัย', 'แปลงพ่อทวีชัย บ้านมณีพฤกษ์ ต.งอบ อ.ทุ่งช้าง จ.น่าน', 50.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-08 22:09:27', '2025-11-08 22:09:27', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (19, NULL, 'แตงม้ง แปลงพ่อบุญช่วย', 'แปลงพ่อบุญช่วย บ้านขุนสถาน ต.สันทะ อ.นาน้อย จ.น่าน_reduced', 43.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-08 22:11:13', '2025-11-29 11:05:01', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (20, NULL, 'เผือก แปลงพ่อบุญช่วย', 'แปลงพ่อบุญช่วย บ้านขุนสถาน ต.สันทะ อ.นาน้อย จ.น่าน_reduced', 50.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-08 22:11:48', '2025-11-29 11:05:43', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (21, NULL, 'ฟักทอง แปลงพ่อบุญช่วย', 'แปลงพ่อบุญช่วย บ้านขุนสถาน ต.สันทะ อ.นาน้อย จ.น่าน_reduced', 29.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-08 22:12:35', '2025-11-29 11:00:07', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (22, NULL, 'ตุ๊กตา', 'ตุ๊กตา', 50.00, 'เครื่องใช้', 'market', NULL, NULL, 100, 0, 11, '2025-11-09 09:40:17', '2025-11-23 21:06:27', 99, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (25, NULL, 'กิ๊บติดผม (ขนาดเล็ก) ผ้ามัดย้อมธรรมชาติ', 'สินค้าจากโครงการผ้ามัดย้อมจากสีธรรมชาติ โรงเรียนมหาชัยวิทยาคม \nซึ่งใช้วัตถุดิบจากพืชที่หาได้ในพื้นที่ เปิดโอกาสให้นักเรียนได้ฝึกทักษะอาชีพ และสามารถนำความรู้ไปต่อยอดสร้างรายได้ระหว่างเรียน ตามแนวทาง “ธรรมชาติ ภูมิปัญญา และการศึกษา”', 49.00, 'เครื่องใช้', 'market', NULL, NULL, 27, 0, 20, '2025-11-12 10:37:43', '2025-11-30 21:35:56', 27, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (31, NULL, 'กระเป๋าผ้าใบใหญ่ ผ้ามัดย้อมธรรมชาติ', 'สินค้าจากโครงการผ้ามัดย้อมจากสีธรรมชาติ โรงเรียนมหาชัยวิทยาคม \nซึ่งใช้วัตถุดิบจากพืชที่หาได้ในพื้นที่ เปิดโอกาสให้นักเรียนได้ฝึกทักษะอาชีพ และสามารถนำความรู้ไปต่อยอดสร้างรายได้ระหว่างเรียน ตามแนวทาง “ธรรมชาติ ภูมิปัญญา และการศึกษา”', 159.00, 'เครื่องใช้', 'market', NULL, NULL, 14, 0, 20, '2025-11-13 14:05:09', '2025-11-30 21:37:27', 14, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (32, NULL, 'กระเป๋าผ้าใบเล็ก ผ้ามัดย้อมธรรมชาติ', 'สินค้าจากโครงการผ้ามัดย้อมจากสีธรรมชาติ โรงเรียนมหาชัยวิทยาคม \nซึ่งใช้วัตถุดิบจากพืชที่หาได้ในพื้นที่ เปิดโอกาสให้นักเรียนได้ฝึกทักษะอาชีพ และสามารถนำความรู้ไปต่อยอดสร้างรายได้ระหว่างเรียน ตามแนวทาง “ธรรมชาติ ภูมิปัญญา และการศึกษา”', 89.00, 'เครื่องใช้', 'market', NULL, NULL, 18, 0, 20, '2025-11-13 14:06:53', '2025-11-30 21:36:44', 18, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (33, NULL, 'พริกขี้หนูสวน', 'พริกขี้หนูสวนจากบ้านพ่อเอนก', 58.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-29 11:02:56', '2025-11-30 18:29:16', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (34, NULL, 'พริกขี้หนู', 'พริกขี้หนูแปลงพ่อเอนก', 58.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-29 11:26:38', '2025-11-29 11:26:38', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (35, NULL, 'พริกหวาน', 'พริกหวานแปลงพ่อชวกร', 86.00, 'ผักผลไม้', 'market', NULL, NULL, 100, 0, 11, '2025-11-29 11:28:11', '2025-11-29 11:28:11', 100, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (37, NULL, 'พวงกุญแจ ผ้ามัดย้อมธรรมชาติ', 'สินค้าจากโครงการผ้ามัดย้อมจากสีธรรมชาติ โรงเรียนมหาชัยวิทยาคม \nซึ่งใช้วัตถุดิบจากพืชที่หาได้ในพื้นที่ เปิดโอกาสให้นักเรียนได้ฝึกทักษะอาชีพ และสามารถนำความรู้ไปต่อยอดสร้างรายได้ระหว่างเรียน ตามแนวทาง “ธรรมชาติ ภูมิปัญญา และการศึกษา”', 69.00, 'เครื่องใช้', 'market', NULL, NULL, 15, 0, 20, '2025-11-30 21:54:37', '2025-12-01 22:22:47', 15, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (43, NULL, 'test', '1', 1.00, 'อาหารแปรรูป', 'market', NULL, NULL, 1, 0, 11, '2025-12-13 18:04:21', '2025-12-13 18:04:21', 1, 1);
INSERT IGNORE INTO `products` (`id`, `project_id`, `title`, `description`, `price`, `category`, `type`, `address`, `coordinate`, `stock_quantity`, `isRecommend`, `user_id`, `created_at`, `updated_at`, `unassigned_stock_quantity`, `next_gallery_image_number`) VALUES (44, NULL, 'test2602', 'test2602', 100.00, 'อื่นๆ', 'market', NULL, NULL, 100, 0, 11, '2026-02-26 21:40:03', '2026-02-26 21:40:03', 100, 1);
-- Development-only product 1 and its local thumbnail fixture.
INSERT INTO `products` (`id`, `user_id`, `title`, `price`, `category`, `type`, `stock_quantity`, `unassigned_stock_quantity`, `isRecommend`, `next_gallery_image_number`) VALUES (1, 1000, 'ชุดผลิตภัณฑ์บำรุงผิวกายจากนมแพะ test', '500.00', 'เครื่องใช้', 'market', 94, 94, 0, 1);
